### ISSUE TITLE
Unable to login, authorization redirects to bsky.social's landing page

### ISSUE THREAD

**Issue by maxfzz** [psky-atp/client#31]
Typing in my handle (`maxfz.xyz`) and clicking login sends me to the authorization process like expected, but clicking accept redirects me to https://bsky.social/about instead of back to picosky. Going back to picosky after that doesn't show me as logged in.

**Comment by maxfzz** [comment]
Tried to log in with my DID, results in the same behavior

**Comment by notjuliet** [comment]
no idea how this could be happening, i havent changed anything
can you confirm to me you are logging through bsky.social and it originated from psky.social

**Comment by maxfzz** [comment]
https://github.com/user-attachments/assets/cfec8acb-e9fc-42e7-a108-7bf48d748f80

**Comment by notjuliet** [comment]
ngl i have no idea how this could be happening
ill look into it but i cant reproduce it on any of my accounts

**Comment by notjuliet** [comment]
is it possible to have request logs with "persist logs" turned on so it doesn't wipe on page navigation

**Comment by DavidBuchanan314** [comment]
Do you have any privacy-related browser extensions installed?

**Comment by maxfzz** [comment]
@notjuliet:

https://github.com/user-attachments/assets/8319945d-fc52-493e-b6cd-37f46f1c6ddc

@DavidBuchanan314:

i do have uBlock Origin and Privacy Badger, i'll try disabling those

**Comment by maxfzz** [comment]
i'm pretty sure this is a firefox issue? managed to "fix" by signing in on chrome and copying the app's localStorage over. after looking at the requests, it seems having a redirect with a url in the query portion (e.g. `?iss=https://bsky.social` for oauth) causes that url to take precedence somehow?

**Comment by maxfzz** [comment]
found the issue in one of my addons, "Skip Redirect", and fixed it by adding a whitelist rule for `://psky.social`
